language: c
sudo: false

env:
  - R_LIBS_USER=~/R/library

cache:
  directories:
    $R_LIBS_USER

before_install:
  - mkdir -p "$R_LIBS_USER"

install:
  - chmod u+x setup.sh && ./setup.sh
  - export PATH=$HOME/texlive/bin/x86_64-linux:$HOME/pandoc/:$HOME/R-bin/bin:$PATH
  - echo "PATH: $PATH"
  - which Rscript
  - Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0L) { install.packages("devtools", repos = "http://cran.rstudio.com") }'
  - Rscript -e 'devtools::update_packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'devtools::install_deps(repos = "http://cran.rstudio.com", dependencies = TRUE)'

script:
  - Rscript -e 'devtools::check()'
