language: c
sudo: false

env:
  - R_LIBS_USER=~/R/library

cache:
  directories:
    $R_LIBS_USER

before_install:
  - mkdir -p "$R_LIBS_USER" ~/R-bin

install:
  - chmod u+x setup.sh && ./setup.sh
  - export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
  - export PATH=$HOME/texlive/bin/x86_64-linux:$HOME/pandoc/:$HOME/R-bin/R-3.2.3/bin:$PATH
  - ls -l $HOME/R-bin/R-3.2.3/bin
  - which Rscript
  - Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0L) { install.packages("devtools", repos = "https://cran.rstudio.com") }'
  - Rscript -e 'devtools::update_packages("devtools", repos = "https://cran.rstudio.com")'
  - Rscript -e 'devtools::install_deps(repos = "https://cran.rstudio.com", dependencies = TRUE)'

script:
  - Rscript -e 'devtools::check()'
