language: R

repos:
  CRAN: "https://cran.rstudio.org"

before_install:
  - cat ~/.Rprofile.site
  - Rscript -e 'options("repos")'
  #- chmod u+x setup.sh;./setup.sh
  #- export PATH=$HOME/R-bin/bin:$PATH
  #- export LD_LIBRARY_PATH=$HOME/R-bin/lib:$LD_LIBRARY_PATH
  #- Rscript -e 'sessionInfo()'
