language: r
sudo: required
os: osx

before_install:
  - echo $R_LIBS_SITE
  - echo $R_LIBS_USER
  - curl -L https://raw.githubusercontent.com/yihui/ubuntu-bin/master/TeXLive.pkgs | xargs sudo tlmgr install
