sudo: required

services:
  - docker

before_install:
  - docker pull rocker/devel
  - docker run -d --name devel -v $(pwd -P):/mnt rocker/devel

script:
  # install package dependencies
  - docker exec devel /bin/sh -c "cd /mnt;Rscript -e 'devtools::install_deps(dep=T);devtools::check()'"
