sudo: required

services:
  - docker

before_install:
  - docker pull bioconductor/devel_base
  - docker run -d --name devel -v $(pwd -P):/mnt bioconductor/devel_base

script:
  # install package dependencies and BiocCheck
  - docker exec devel /bin/sh -c "cd /mnt;Rscript -e 'devtools::install_deps(dep=T);devtools::check()'
