language: R

bioc_required: false

cache: packages

before_install:
  - cat ~/.Rprofile
  - Rscripte -e 'options("repos")'

  - locate .Rprofile
  #- chmod u+x setup.sh;./setup.sh
  #- export PATH=$HOME/R-bin/bin:$PATH
  #- export LD_LIBRARY_PATH=$HOME/R-bin/lib:$LD_LIBRARY_PATH
  #- Rscript -e 'sessionInfo()'
  - echo "$_R_CHECK_CRAN_INCOMING_"
