language: R

repos:
  - CRAN: "http://cran.rstudio.org"
  - ropensci: "packages.ropensci.org"

bioc_required: true

cache: packages

before_install:
  - cat ~/.Rprofile
  - Rscript -e 'options("repos")'
  #- chmod u+x setup.sh;./setup.sh
  #- export PATH=$HOME/R-bin/bin:$PATH
  #- export LD_LIBRARY_PATH=$HOME/R-bin/lib:$LD_LIBRARY_PATH
  #- Rscript -e 'sessionInfo()'
  - echo "$_R_CHECK_CRAN_INCOMING_"
